### ISSUE TITLE
wrong demo codes

### ISSUE THREAD

**Issue by xltank** [niklaus0823/word-filter-dfa#1]
const wordFilter = require('word-filter-dfa').WordFilter.instance();
wordFilter.init(badwords);
let r = wordFilter.replace('I'm bad words...');

**Comment by niklaus0823** [comment]
Thank you for your issue. This surely is the issue shall be fixed in v0.0.3.

**Comment by niklaus0823** [comment]
Latest version 0.0.3 has been published.
